travis:
  secure:
    BINSTAR_TOKEN: OOdz+u/603Qn7qMkg+ijh0wVpD0W0YQJD4Lxiw6DQ54GJvlIx23ppWWsZEtTA0xbS/rwusyGhOE5iEuFUTy0KxtaBrShviwRLq+PGphxL9AYDsG1jxEzQExcYlcwJWzFAP/h03dBSlZErMBT5qT3SlD6cwEyCODqWLNHjwPKQglK+Ah25KeLKHWbXtAsgU3ueltj9+4QJjMS6Je4EnMEDTKBKkHCQIADC7fFJOUV1SUZtRWSYASP+n0Z81PqUhM/wvW7MxJ0PE+bzL/OQ15VQdxTNi8mOiOAoXz0/0Lk5zgeFoqlk57cSaa++6t+V6SCF+nL2IonFSsrBzcbkubHD4k47BE9Tc4YlMiJCJQhh43j1qbIqGFZ6+lwHaNG1/+3uBJg/8mU0hFoJT+Yuuf2j/HxFx9MPlZF+hy/nqVJafb7gdxLyBTIleVARSuwGUk4brKa+nL1xjJt2tnuTGoGS/QzZodY2R+wzTh68RMI+N5RM3fIbV86WcSPfSNSKObZ+41b7R8/60ANhz3KIQhoDB7OiFiyaYGVt+aCiIz8xrX7Y7EKJ+jUc8bh+MfIQvRA9+5/bWkM1SpgVfPiziUs2GbvIa83xwA5/2VF0aoxFuCunBsbeGev1tiDE/pTHhiU7Lu+0fUhUUxedYZtAg7s1RtRrGPh3Y5mSm0NqAKRzZg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
