travis:
  secure:
    BINSTAR_TOKEN: awq+EJTm9N+lC/f0z+E/vHuLHGHijYFDfP0o9kvX/l7tKdmb5rHSmih1HRn1vOXLqaiw2sMfgOkTBVwh7AjWjDk/+76se/4AhABU+c37chr8irzG9zvYEFJfaXRNO7B6O+JGJdzIACb+roaUQlW5oqA/2aE2AhUdrlC44YGDA2/CGQGof6hEhVINmdOgnOqZFAIYcJwIzSWkAFus+Q/MM/9lB9cJapYbIfhgINWwGQA29tXIs775f2URBo6n1tcdmi7Fq+x5pYDfCJQiy6ICVURbhXZbPstNiNP+dsm48V+wtfsT8cRMwWsMJjab/s2L0LILuBFZnGkBWyn6SG/bZ3FUayPCVwkLB4c8A75Dv769eWTOpJa8+xAZVTAYqL5C8mhsg4BoHS38dY/E+HoztXsXdEkhiVF2ov1+cIZxnRgtaJ6zzN4cubMotCVkspuymyo7YE6cKmC2HJy2jkrtUlKM2cyzDAgTQqMV3GnBdoMeimDnhLieKXWfhUjDLvLI/kjBJu+bivPXnZ6M/FsbqoTKf9500Gf5ql971/pTN9rtPqx6tTgbQopA4MbLUtgA5OpdytRAHZsHnnESKIJme39pyz4E0thjOP8A/qxLxByNT/50NI4XbtHYgOfc3veR+cxmd4Dg5aAAJeIn86UgqHhXizqsqjBAIy9C+8BM/nc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
