travis:
  secure:
    BINSTAR_TOKEN: eGTVSTQZnKbLlttVKomsr01gGg9Rt07GARsL62noRkDMxS0O77qU5fHsNBIciRWoYXNfTsFsYKK6U32fGKx7V4MJ16NjT4C+gPxsaEkg548yEuDt/4mzUt44wQk5aajl/u9kbooKVV+GuLkE/B4Ew620VVSUnu/sPwQyfY0ov16GMfxOiJuUY090LIINo/msmJ5dOk2bWM+uae9YsQDFJSpRC33hIdf2T3Y2nzfRfVUen6IiG/sDg9xpIwAT/oCZ01z16AoddOFA3gv4v466rfiCfyvV5/JRDg5JMUizXrlSDoBmgroTBRi44sCY5l+WfX8/Q8qurXcxoAHhhQuYIqE4htzpOhPbHaMBN4TA84PUZplVJ9Xa0JOd7/28/pk44fbXpOobGnSybLnpu/PnMB5TPgwznUUJcy4crzQipeMtsFRCt422NZr5Iuh1EyHWz2vfQE/QI7FtrHdZa6NKo7rYMx2SExLUmQ6PfeF7wxDGccntf6iiMfQyTXikEiUldNjiF3v5lpAOTtgH1bq3KNgIPZbDBHpybJBR2rOlHLRgFUBuDplhB9HBWNcy9lquiAbT7Yfj05tE8+MDifPrOv8yUdiskeiNxSwQd7WL4Jdkg5EPRP+NsyJvonB3vG4aVH3DPPKr/bHuKxtfcfZebsNuac3guKeelZihknWiqpo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
